FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npx prisma generate

COPY src ./src
COPY assets ./assets
COPY scripts ./scripts

EXPOSE 3000

CMD ["npm", "start"]